### Confusion Matrix

Ref : https://www.analyticsvidhya.com/blog/2020/04/confusion-matrix-machine-learning/

<img src="image/Matrics.jpg" width="250">

<img src="image/Formula.jpg" width="500">

In [3]:
from sklearn.metrics import confusion_matrix
import numpy as np

# n_n = np.array([[2385,  4,   0,   1,   4],
#                 [0   ,332,   0,   0,   1],
#                 [0   ,  1, 908,   8,   0],
#                 [0   ,  0,   0,1084,   9],
#                 [12  ,  0,   0,   6,2053]])

# _class = ["Asphalt", "Concrete", "Grass",'Tree','Building']

# For Binary Classification matrics should follow these sequences
##  [TP FP]
##  [FN TN]

from sklearn.metrics import confusion_matrix

y_true = ['Cat', 'Dog', 'Rabbit', 'Cat', 'Cat', 'Rabbit']
y_pred = ['Dog', 'Dog', 'Rabbit', 'Dog', 'Dog', 'Rabbit']

_class=['Cat', 'Dog', 'Rabbit']

n_n = confusion_matrix(y_true, y_pred, labels=['Cat', 'Dog', 'Rabbit'])


if n_n.shape[0]==n_n.shape[1]:
    print('input matrics shape correct')
    print(n_n)
    
    for i in range(len(_class)):        
        
        print('Class Name - {}'.format(_class[i]))

        TP = n_n[i,i]                                              ## Diagonal one
        FP = n_n[i].sum() - TP                                     ## Same Row except TP 
        TN = n_n.sum() - n_n[i].sum() - n_n[:,i].sum() + n_n[i,i]
        FN = n_n[:,i].sum() - TP                                   ## Same Column except TP

        print('\t TP = {} | FP = {} | TN = {} | FN = {}'.format(TP,FP,TN,FN))
        print('\t Accuracy  - {}%'.format( round(((TP+TN)/(TP+FP+TN+FN))*100,2)))
        precision = ((TP)/(TP+FP))*100
        print('\t Precision - {}%'.format( precision ))

        recall    = ((TP)/(TP+FN))*100
        print('\t Recall    - {}%'.format( recall ))

        print('\t F1=Score  - {}%'.format( round(2/(1/recall+1/precision),2)))

input matrics shape correct
[[0 3 0]
 [0 1 0]
 [0 0 2]]
Class Name - Cat
	 TP = 0 | FP = 3 | TN = 3 | FN = 0
	 Accuracy  - 50.0%
	 Precision - 0.0%
	 Recall    - nan%
	 F1=Score  - nan%
Class Name - Dog
	 TP = 1 | FP = 0 | TN = 2 | FN = 3
	 Accuracy  - 50.0%
	 Precision - 100.0%
	 Recall    - 25.0%
	 F1=Score  - 40.0%
Class Name - Rabbit
	 TP = 2 | FP = 0 | TN = 4 | FN = 0
	 Accuracy  - 100.0%
	 Precision - 100.0%
	 Recall    - 100.0%
	 F1=Score  - 100.0%


<ipython-input-3-287c395bd4f1>:40: RuntimeWarning: invalid value encountered in longlong_scalars
  recall    = ((TP)/(TP+FN))*100
<ipython-input-3-287c395bd4f1>:43: RuntimeWarning: divide by zero encountered in double_scalars
  print('\t F1=Score  - {}%'.format( round(2/(1/recall+1/precision),2)))


In [41]:
# 2nd column of
X[:,0]

array([12,  7,  1])

In [35]:
# 2nd column of
X[1]

array([7, 6, 8, 8])